### PR TITLE
Add Call URL with Authentication

### PR DESCRIPTION
**Pull request by mohamed25-dev**
Some API's need authentication so I added a new method that accept username and password and then encode them after that it adds the encoded String to the header.

### CODE REVIEW

**Comment by motaz** [comment]
what encoding type do you mean? is it URL encode?

**Comment by mohamed25-dev** [comment]
No, it is normal encoding(if I can name it like that :) ) before adding the credentials to the URL

**Comment by motaz** [comment]
Ok, I get it, but is that a special case of an application, or a general method of passing username/password encrypted that can be useful for may applications?

**Review by motaz — APPROVED** [review]

**Comment by motaz** [comment]
I have approved the commit, I thought that you are asking for this feature rather than developing it

**Comment by mohamed25-dev** [comment]
It is a special case, I faced it with one of our clients API's

**Pull request merged**
